### ISSUE TITLE
Configure the repo up for release

### ISSUE THREAD

**Issue by eddiecarpenter** [quarkiverse/quarkus-jdiameter#13]
What is the process for configuring the quarkus-jdiameter repo for releasing artefacts to Maven?

Where does one load the GPG_SECRETKEY variable? The repo's setting tab does not have the "Secrets and Variable" option.

**Comment by gastaldi** [comment]
To release just follow these steps: https://hub.quarkiverse.io/release/

The PR must be created from a branch in this repository, do not use a forked repository

**Comment by eddiecarpenter** [comment]
Thanks for the help - It worked!
