### ISSUE TITLE
Quarkus JDiameter extension spotligh on Quarkus Insights?

### ISSUE THREAD

**Issue by insectengine** [quarkiverse/quarkus-jdiameter#33]
@eddiecarpenter - Hi Eddie,

I'm James Cobb and I work with Max Andersen and Holly Cummins to help schedule Quarkus Insights. We were discussing topics for upcoming sessions and the Quarkus JDiameter extension came to mind.

Would you be interested in being a guest on the podcast? I see you're in Auckland. The podcast is done live on Mondays at 3pm (GMT+2) 9am Eastern time in the US.

**Comment by insectengine** [comment]
I created a github issue for this topic: 
https://github.com/quarkusio/quarkus-insights/issues/235

**Comment by eddiecarpenter** [comment]
Accepted and scheduled for the 30th of September
