### ISSUE TITLE
Duplicate  TCPClientConnection.class

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-jdiameter#38]
Just eyeballing your code it looks like this class is inclduded twice.

https://github.com/quarkiverse/quarkus-jdiameter/blob/1ac1bc5c87616392b4b939a172d265aca01d1910/quarkus-diameter/deployment/src/main/java/io/quarkiverse/diameter/deployment/DiameterProcessor.java#L101-L102

**Comment by eddiecarpenter** [comment]
Well spotted, thanks!
